language: ruby
before_install:
  - curl -L https://packagecloud.io/hughrawlinson/chuck/gpgkey | sudo apt-key add -
  - sudo apt-get install -y apt-transport-https
  - echo "deb https://packagecloud.io/hughrawlinson/chuck/ubuntu/ trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y chuck sox
script:
  - bash render.sh
cache:
  directories:
  - data
sudo: required
dist: trusty
